#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using TowerDefense.Data.EntityData;

namespace TowerDefense.Editor.EntityData
{
    public static class EntityIdEnumGenerator
    {
        public static string OutputPath =>
            "Assets/Scripts/TowerDefense/Data/EntityData/Generated/EntityId.g.cs";

        public static void Generate(EntityConfigRegistryAsset registry)
        {
            if (registry == null)
                throw new ArgumentNullException(nameof(registry));

            var lines = new List<string>
            {
                "// Auto-generated by EntityIdEnumGenerator. Do not edit manually.",
                "namespace TowerDefense.Data.EntityData",
                "{"
            };

            foreach (EntityType entityType in Enum.GetValues(typeof(EntityType)))
            {
                if (entityType == EntityType.Max)
                    continue;

                string enumTypeName = GetEnumTypeName(entityType);
                lines.Add($"    public enum {enumTypeName}");
                lines.Add("    {");
                lines.Add("        None = 0,");

                int localId = 1;
                var usedNames = new HashSet<string>(StringComparer.Ordinal);
                foreach (var record in registry.MutableRecords
                             .Where(x => x.EntityType == entityType)
                             .OrderBy(x => x.EntityIdToken, StringComparer.Ordinal))
                {
                    string enumName = string.IsNullOrWhiteSpace(record.EntityIdEnumName)
                        ? Sanitize(record.DisplayName)
                        : Sanitize(record.EntityIdEnumName);
                    if (!usedNames.Add(enumName))
                        throw new InvalidOperationException($"Duplicate enum name in {entityType}: {enumName}");

                    record.LocalId = localId;
                    record.EntityIdEnumName = enumName;
                    lines.Add($"        {enumName} = {localId},");
                    localId++;
                }

                lines.Add($"        Max = {localId}");
                lines.Add("    }");
                lines.Add(string.Empty);
            }

            lines.Add("}");

            string absolutePath = Path.GetFullPath(OutputPath);
            string directory = Path.GetDirectoryName(absolutePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            File.WriteAllText(absolutePath, string.Join("\n", lines), Encoding.UTF8);
        }

        public static string Sanitize(string raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return "UNKNOWN";

            var builder = new StringBuilder(raw.Length);
            for (int i = 0; i < raw.Length; i++)
            {
                char c = raw[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                    builder.Append(char.ToUpperInvariant(c));
                else
                    builder.Append('_');
            }

            string normalized = builder.ToString().Trim('_');
            if (string.IsNullOrEmpty(normalized))
                normalized = "UNKNOWN";
            if (char.IsDigit(normalized[0]))
                normalized = $"ID_{normalized}";
            return normalized;
        }


        private static string GetEnumTypeName(EntityType entityType)
        {
            switch (entityType)
            {
                case EntityType.TURRET:
                    return "TurretId";
                case EntityType.ENEMY:
                    return "EnemyId";
                case EntityType.PROJECTILE:
                    return "ProjectileId";
                default:
                    throw new ArgumentOutOfRangeException(nameof(entityType), entityType, null);
            }
        }
    }
}
#endif

